# Generated by Django 4.0.1 on 2022-01-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_alter_albums_caption_alter_albums_font_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='published',
            new_name='publishe',
        ),
    ]
