# Generated by Django 4.0.1 on 2022-01-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_rename_published_albums_publishe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='publishe',
            new_name='publish',
        ),
    ]
