# Generated by Django 4.0.1 on 2022-01-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_rename_position_coordinates_rights_albums_position_coordinates_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafts',
            name='album',
        ),
        migrations.AddField(
            model_name='drafts',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gram.albums'),
            preserve_default=False,
        ),
    ]
